### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by toollu** [simon-mettler/tagi-paywall-remover#1]
First: Thanks for the great work! Unfortunately I'm an absolute noob in js and cannot contribute it myself, but would it be possible to include also the subdomain interaktiv.tagesanzeiger.ch ? Of course only for demonstration purposes.

**Comment by simon-mettler** [comment]
Should now work...
Since they use the same paywall-setup, it's as simple as getting the plugin activated on the mentioned subdomain.

https://github.com/simon-mettler/tagi-paywall-remover/blob/4855d1529c962c200fd126fff2242a9229b3d901/manifest.json#L24-L28
